# Generated by Django 5.0.7 on 2024-09-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_rename_productrating_productuserrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seles_persent',
            new_name='sales_percent',
        ),
    ]
