# Generated by Django 5.0.7 on 2024-09-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_rename_seles_persent_product_sales_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productuserrating',
            old_name='users',
            new_name='user',
        ),
    ]
