# Generated by Django 5.0.7 on 2024-09-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_rename_users_productuserrating_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productuserrating',
            unique_together={('user', 'product')},
        ),
    ]
