# Generated by Django 5.0.7 on 2024-09-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_productuserrating_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productuserrating',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterUniqueTogether(
            name='productuserrating',
            unique_together={('users', 'product')},
        ),
    ]
