# Generated by Django 5.0.7 on 2024-10-04 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_favoriteproduct_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteProduct',
        ),
    ]
