# Generated by Django 5.0.7 on 2024-10-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_delete_favoriteproduct'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_product',
            field=models.ManyToManyField(to='market.product'),
        ),
    ]
