# Generated by Django 5.0.7 on 2024-10-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_favorite_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='favorite_product',
            new_name='favorite_products',
        ),
    ]
